# Generated by Django 5.0.1 on 2024-03-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filerobot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designstate',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Design State', 'verbose_name_plural': 'Design States'},
        ),
    ]
