from django.conf import settings as _settings


FILEROBOT_USER_MUST_MATCH = getattr(_settings, "FILEROBOT_USER_MUST_MATCH", False)
FILEROBOT_DISABLE_HISTORY = getattr(_settings, "FILEROBOT_DISABLE_HISTORY", False)

FILEROBOT_COLLECTION_NAME = getattr(_settings, "FILEROBOT_COLLECTION_NAME", "filerobot")
FILEROBOT_COLLECTION_CACHE_KEY = getattr(_settings, "FILEROBOT_COLLECTION_CACHE_KEY", f"FILEROBOT:{FILEROBOT_COLLECTION_NAME}")
FILEROBOT_COLLECTION_CACHE_TIMEOUT = getattr(_settings, "FILEROBOT_COLLECTION_CACHE_TIMEOUT", 60 * 60 * 24 * 7)
